--
-- Sample dataset of ATP players.
--

-- =================================================================================================
-- Players

--insert into city(country, name, state, map) values ('Australia', 'Brisbane', 'Queensland', '-27.470933, 153.023502')
insert into player(first_name, surname, represents, image) values ('Novak', 'Djokovic', 'SRB', 'djokovic.png')
insert into player(first_name, surname, represents, image) values ('Roger', 'Federer', 'SUI', 'federer.png')
insert into player(first_name, surname, represents, image) values ('Andy', 'Murray', 'GBR', 'murray.png')
insert into player(first_name, surname, represents, image) values ('Rafael', 'Nadal', 'ESP', 'nadal.png')
insert into player(first_name, surname, represents, image) values ('Stan', 'Wawrinka', 'SUI', 'wawrinka.png')
insert into player(first_name, surname, represents, image) values ('Thomas', 'Berdych', 'CZH', 'berdych.png')
insert into player(first_name, surname, represents, image) values ('Milos', 'Raonic', 'CAN', 'raonic.png')
insert into player(first_name, surname, represents, image) values ('Richard', 'Gasquet', 'FRA', 'gasquet.png')
insert into player(first_name, surname, represents, image) values ('Marcos', 'Baghdatis', 'CYR', 'baghdatis.png')
insert into player(first_name, surname, represents, image) values ('Mario', 'Cilic', 'CRO', 'cilic.png')
insert into player(first_name, surname, represents, image) values ('Grigor', 'Dimitrov', 'BUL', 'dimitrov.png')
insert into player(first_name, surname, represents, image) values ('Alexander', 'Dolgopolov', 'UKR', 'dolgopolov.png')
insert into player(first_name, surname, represents, image) values ('Ernest', 'Gulbis', 'LAT', 'gulbis.png')
insert into player(first_name, surname, represents, image) values ('Fabio', 'Fognini', 'ESP', 'fognini.png')
insert into player(first_name, surname, represents, image) values ('Sam', 'Groth', 'AUS', 'groth.png')
insert into player(first_name, surname, represents, image) values ('David', 'Ferrer', 'ESP', 'ferrer.png')
insert into player(first_name, surname, represents, image) values ('John', 'Isner', 'USA', 'isner.png')
insert into player(first_name, surname, represents, image) values ('Nick', 'Kyrgios', 'AUS', 'kyrgios.png')
insert into player(first_name, surname, represents, image) values ('Gael', 'Monfils', 'FRA', 'monfils.png')
insert into player(first_name, surname, represents, image) values ('Bernard', 'Tomic', 'AUS', 'tomic.png')
insert into player(first_name, surname, represents, image) values ('Tommy', 'Robredo', 'ESP', 'robredo.png')
insert into player(first_name, surname, represents, image) values ('Kei', 'Nishikori', 'JPN', 'nishikori.png')
insert into player(first_name, surname, represents, image) values ('Fernando', 'Verdasco', 'ESP', 'verdasco.png')
insert into player(first_name, surname, represents, image) values ('Jo-Wilfred', 'Tsonga', 'FRA', 'tsonga.png')
insert into player(first_name, surname, represents, image) values ('Andreas', 'Seppi', 'ITA', 'seppi.png')
insert into player(first_name, surname, represents, image) values ('Philipp', 'Kohlschreiber', 'GER', 'kohlschreiber.png')
insert into player(first_name, surname, represents, image) values ('Thannasi', 'Kokkinakis', 'AUS', 'kokkinakis.png')
insert into player(first_name, surname, represents, image) values ('Michael', 'Llodra', 'FRA', 'llodra.png')
insert into player(first_name, surname, represents, image) values ('Jerzy', 'Janowicz', 'POL', 'janowicz.png')
insert into player(first_name, surname, represents, image) values ('Benoit', 'Paire', 'FRA', 'paire.png')
insert into player(first_name, surname, represents, image) values ('Gilles', 'Simon', 'FRA', 'simon.png')
insert into player(first_name, surname, represents, image) values ('Feliciano', 'Lopez', 'ESP', 'lopez.png')